export const GET_CATEGORY_ITEMS = "GET_CATEGORY_ITEMS";
export const GET_CATEGORY_ITEMS_FULFILLED = "GET_CATEGORY_ITEMS_FULFILLED";
export const GET_CATEGORYS = "GET_CATEGORYS";
export const GET_CATEGORYS_FULFILLED = "GET_CATEGORYS_FULFILLED";
export const GET_DETAIL_ITEM = "GET_DETAIL_ITEM";
